FROM vllm/vllm-openai:v0.5.1

RUN yes| unminimize

# Set ENV variables
ENV LANG C.UTF-8
ENV SHELL=/bin/bash
ENV DEBIAN_FRONTEND=noninteractive

ENV APT_INSTALL="apt-get install -y --no-install-recommends"
ENV PIP_INSTALL="python3 -m pip --no-cache-dir install --upgrade"
ENV GIT_CLONE="git clone --depth 10"

RUN mkdir -p /home/setup
RUN mkdir -p /home/projects

WORKDIR /home/setup
COPY ./code-installation.sh /home/setup/code-installation.sh


RUN apt-get update && \
    $APT_INSTALL \
    gcc \
    make \
    pkg-config \
    apt-transport-https \
    build-essential \
    apt-utils \
    ca-certificates \
    wget \
    rsync \
    git \
    vim \
    mlocate \
    libssl-dev \
    curl \
    openssh-client \
    unzip \
    unrar \
    zip \
    csvkit \
    emacs \
    joe \
    jq \
    dialog \
    nano \
    iputils-ping \
    sudo \
    ffmpeg \
    libsm6 \
    libxext6 \
    libboost-all-dev \
    gnupg \
    cifs-utils \
    zlib1g \
    software-properties-common


# Make the script executable
RUN chmod +x /code-installation.sh

# Run the script
RUN /bin/bash /code-installation.sh

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash && \
        $APT_INSTALL git-lfs

RUN $PIP_INSTALL jupyterlab

# ==================================================================
# Installing JRE and JDK
# ------------------------------------------------------------------

RUN $APT_INSTALL \
    default-jre \
    default-jdk


# ==================================================================
# Node.js and Jupyter Notebook Extensions
# ------------------------------------------------------------------
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash  && \
    $APT_INSTALL nodejs 
RUN python3 -m pip install --upgrade jupyter
            

# ==================================================================
# Startup
# ------------------------------------------------------------------
WORKDIR /home/projects

EXPOSE 8888 6006

ENTRYPOINT ["jupyter", "lab", "--allow-root", "--ip=0.0.0.0", "--no-browser", "--ServerApp.trust_xheaders=True", "--ServerApp.disable_check_xsrf=False", "--ServerApp.allow_remote_access=True", "--ServerApp.allow_origin='*'", "--ServerApp.allow_credentials=True"]