FROM vllm/vllm-openai:v0.5.3.post1

RUN yes| unminimize

# Set ENV variables
ENV LANG C.UTF-8
ENV SHELL=/bin/bash
ENV DEBIAN_FRONTEND=noninteractive

ENV APT_INSTALL="apt-get install -y --no-install-recommends"
ENV PIP_INSTALL="python3 -m pip install"
ENV GIT_CLONE="git clone --depth 10"

RUN mkdir -p /home/setup
RUN mkdir -p /home/projects

WORKDIR /home/setup
COPY ./code-installation.sh /home/setup/code-installation.sh


RUN apt-get update && \
    $APT_INSTALL \
    gcc \
    make \
    pkg-config \
    apt-transport-https \
    build-essential \
    apt-utils \
    ca-certificates \
    wget \
    rsync \
    git \
    vim \
    mlocate \
    libssl-dev \
    curl \
    openssh-client \
    unzip \
    unrar \
    zip \
    csvkit \
    emacs \
    joe \
    jq \
    dialog \
    nano \
    iputils-ping \
    sudo \
    ffmpeg \
    libsm6 \
    libxext6 \
    libboost-all-dev \
    gnupg \
    cifs-utils \
    zlib1g \
    software-properties-common

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash && \
        $APT_INSTALL git-lfs

RUN $PIP_INSTALL jupyterlab

# ==================================================================
# Installing JRE and JDK
# ------------------------------------------------------------------

RUN $APT_INSTALL \
    default-jre \
    default-jdk


# ==================================================================
# Node.js and Jupyter Notebook Extensions
# ------------------------------------------------------------------
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash  && \
    $APT_INSTALL nodejs 
RUN python3 -m pip install --upgrade jupyter

# ==================================================================
# Install VS Code
# ------------------------------------------------------------------
RUN chmod +x /home/setup/code-installation.sh && \
    /home/setup/code-installation.sh

# ==================================================================
# Install ngrok
# ==================================================================
RUN curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
    sudo gpg --dearmor -o /etc/apt/keyrings/ngrok.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/ngrok.gpg] https://ngrok-agent.s3.amazonaws.com buster main" | \
    sudo tee /etc/apt/sources.list.d/ngrok.list && \
    sudo apt update && sudo apt install ngrok
            
# ==================================================================
# Startup
# ------------------------------------------------------------------
WORKDIR /home/projects

EXPOSE 8888 6006

# Copy the startup script into the image
COPY startup.sh /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/startup.sh

# Use the startup script as the entrypoint
ENTRYPOINT ["/usr/local/bin/startup.sh"]

# ENTRYPOINT ["jupyter", "lab", "--allow-root", "--ip=0.0.0.0", "--no-browser", "--ServerApp.trust_xheaders=True", "--ServerApp.disable_check_xsrf=False", "--ServerApp.allow_remote_access=True", "--ServerApp.allow_origin='*'", "--ServerApp.allow_credentials=True", "--notebook-dir=/home/projects"]